// AUTO-GENERATED by scripts/build-brand.mjs — do not edit by hand.
export type ClientLogo = { slug: string; name: string; w: number; h: number };

/** Client and partner logos, normalised to a common optical height. */
export const clientLogos: ClientLogo[] = [
  {
    "slug": "asian-paints",
    "name": "Asian Paints",
    "w": 156,
    "h": 128
  },
  {
    "slug": "assam-building",
    "name": "Assam Building & Other Construction Workers Welfare Board",
    "w": 116,
    "h": 128
  },
  {
    "slug": "astral",
    "name": "Astral Pipes",
    "w": 303,
    "h": 128
  },
  {
    "slug": "asdc",
    "name": "Automotive Skills Development Council",
    "w": 248,
    "h": 128
  },
  {
    "slug": "bcpl",
    "name": "BCPL",
    "w": 93,
    "h": 128
  },
  {
    "slug": "bharat-petroleum",
    "name": "Bharat Petroleum",
    "w": 87,
    "h": 128
  },
  {
    "slug": "boeing",
    "name": "Boeing",
    "w": 316,
    "h": 128
  },
  {
    "slug": "bsf",
    "name": "Border Security Force",
    "w": 121,
    "h": 128
  },
  {
    "slug": "castrol",
    "name": "Castrol",
    "w": 296,
    "h": 128
  },
  {
    "slug": "cgsc",
    "name": "Chhattisgarh Skill Development Council",
    "w": 221,
    "h": 128
  },
  {
    "slug": "csdc",
    "name": "Construction Skill Development Council",
    "w": 173,
    "h": 128
  },
  {
    "slug": "credai",
    "name": "CREDAI",
    "w": 392,
    "h": 128
  },
  {
    "slug": "crisp",
    "name": "CRISP",
    "w": 218,
    "h": 128
  },
  {
    "slug": "dilip-buildocon",
    "name": "Dilip Buildcon",
    "w": 189,
    "h": 128
  },
  {
    "slug": "envalior",
    "name": "Envalior",
    "w": 278,
    "h": 128
  },
  {
    "slug": "essilor-luxottica",
    "name": "EssilorLuxottica",
    "w": 429,
    "h": 128
  },
  {
    "slug": "godrej-aerospace",
    "name": "Godrej Aerospace",
    "w": 372,
    "h": 128
  },
  {
    "slug": "hettich",
    "name": "Hettich",
    "w": 173,
    "h": 128
  },
  {
    "slug": "bhartiya-vayu-sena",
    "name": "Indian Air Force",
    "w": 113,
    "h": 128
  },
  {
    "slug": "indian-army",
    "name": "Indian Army",
    "w": 178,
    "h": 128
  },
  {
    "slug": "indian-oil",
    "name": "Indian Oil",
    "w": 105,
    "h": 128
  },
  {
    "slug": "jaquar",
    "name": "Jaquar",
    "w": 326,
    "h": 128
  },
  {
    "slug": "jsw",
    "name": "JSW",
    "w": 228,
    "h": 128
  },
  {
    "slug": "mssds",
    "name": "Meghalaya State Skill Development Society",
    "w": 305,
    "h": 128
  },
  {
    "slug": "nsdc",
    "name": "National Skill Development Corporation",
    "w": 291,
    "h": 128
  },
  {
    "slug": "north-eastern-council",
    "name": "North Eastern Council",
    "w": 128,
    "h": 128
  },
  {
    "slug": "orientbell",
    "name": "Orientbell Tiles",
    "w": 293,
    "h": 128
  },
  {
    "slug": "reliance-foundation",
    "name": "Reliance Foundation",
    "w": 241,
    "h": 128
  },
  {
    "slug": "shreeji-infra",
    "name": "Shreeji Infrastructure",
    "w": 264,
    "h": 128
  },
  {
    "slug": "tata",
    "name": "Tata",
    "w": 146,
    "h": 128
  },
  {
    "slug": "total-energies",
    "name": "TotalEnergies",
    "w": 128,
    "h": 128
  },
  {
    "slug": "veedol",
    "name": "Veedol",
    "w": 282,
    "h": 128
  },
  {
    "slug": "wmpsc",
    "name": "Water Management and Plumbing Skill Council",
    "w": 181,
    "h": 128
  }
];

/** Every logo asset shares this intrinsic height; width varies. */
export const LOGO_H = 128;

export const wordmark = {
  colour: { src: "/brand/yandnow.webp", w: 837, h: 184 },
  white: { src: "/brand/yandnow-white.webp", w: 837, h: 184 },
};
