// AUTO-GENERATED by scripts/build-images.mjs — do not edit by hand.
// Curated selection from the programme photo archive, 2020–2026.
export type Photo = { src: string; w: number; h: number; blur: string };

export const photos = {
  "welding-sparks": {
    "src": "/img/welding-sparks.webp",
    "w": 1800,
    "h": 1013,
    "blur": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoQAAkAA8BgJYwCdAEIXVqW4AD+RWkgsJvnp6L9n7RD9WzdYdaD414uWuPAGOFSbPKecI1yho2feOmGYIvpqHvLvoAAAA=="
  },
  "engine-cohort": {
    "src": "/img/engine-cohort.webp",
    "w": 1800,
    "h": 1013,
    "blur": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoQAAkAA8BgJQBdgCB+8BuZWkAAzgyWJKetACsVrObOkwTjjBzbbUcQRdpzT2Y3R3keS9c/vJEGzdjXeHymEYiper/tpbRowAA="
  },
  "welding-bay": {
    "src": "/img/welding-bay.webp",
    "w": 1400,
    "h": 1050,
    "blur": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAQAgCdASoQAAwAA8BgJQBOgB9gw+NA+nAAAP2/wS9DtK0muv7XOxdcXexyCbnlro2y8I26NdiLPS4HTkG5kJa/11YuCiKiWbetrJZmM1FXJWabmQQL9zRrEgsM4A9xZqu8AIFBjBUuiGkAAAA="
  },
  "welding-shield": {
    "src": "/img/welding-shield.webp",
    "w": 1400,
    "h": 1050,
    "blur": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAABQAgCdASoQAAwAA8BgJYgC7AYr7jVq5DY48AAAzjp2vBLf8DB8RcY9dtvT1Ky/WprvzkO5pFKYvA72jPN2jQOR4Zm1pKjRNHAwxkD3sKeA7L9j0rN+M4VXoWhc3x9e74clwcBEoMFyDV4+AAA="
  },
  "defence-engine-class": {
    "src": "/img/defence-engine-class.webp",
    "w": 1800,
    "h": 1013,
    "blur": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoQAAkAA8BgJZQCdADcrM4vv0AA/eH/vrjlHOUU5Q2NkZydYtyH4KndFiBqB3QldaAC3tsJ978WdLcc4myfIZ2ktkUgAA=="
  },
  "defence-mobile-unit": {
    "src": "/img/defence-mobile-unit.webp",
    "w": 1800,
    "h": 1013,
    "blur": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAACQAQCdASoQAAkAA8BgJYwAAlTPtqAA/mCyhw3YGA73ucyHrmTJR4UeUSf6TXCzH4xcGou4YpGG9H6gsmkBKP7Vhtmi2GOVwVeTti46zf9eKjyap0AAAA=="
  },
  "defence-assembly": {
    "src": "/img/defence-assembly.webp",
    "w": 1800,
    "h": 1013,
    "blur": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoQAAkAA8BgJYgC7ADzpyuF9fAA/kSKrFLRxZBcPN17szBNLC7Xc70AW1Iz7W9m4RSGmR3N20HsK6s+G3+K5fqSWk1I0TkKIAA="
  },
  "helmet-engine-lab": {
    "src": "/img/helmet-engine-lab.webp",
    "w": 1400,
    "h": 1050,
    "blur": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAAAwAgCdASoQAAwAA8BgJYgCdAYvrGZv5ElRgADeVKwgRJxH6yLlR+j+n/wcmP6wty9Y9GoNMym9xHP9ftrcBUGfD76Z6eSe9bseRUicx+aUzvIzZ+ohoTncOfiZovRZwESfNBuBCtoDD0AA"
  },
  "mobile-training-unit": {
    "src": "/img/mobile-training-unit.webp",
    "w": 1800,
    "h": 1013,
    "blur": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACwAQCdASoQAAkAA8BgJYwCw7EI+lcgAP38mUV7zpU9VPdEVj77C3cymOaBc27j2fYTXa5Sz5aIS4K45fMu3SRYuvBIcMg446AAAA=="
  },
  "car-lift-training": {
    "src": "/img/car-lift-training.webp",
    "w": 1400,
    "h": 1750,
    "blur": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAAAwBACdASoQABQAPwForE6rJaQiMAgBYCAJZQDCgBMhwovdbx5HEmeX7gAA/swAS0QvEKCyybyyd+pSt4b2JLbGYAR4/Kn3ZGLz2r2gPvPD65ssyfm+d3WKqmxYmWHEEkyl/7VJTFZ9/OLpXW924PECL6x9sscuNOQBYv5jUWK31yjgnCx9k8IqYAA="
  },
  "undercarriage-check": {
    "src": "/img/undercarriage-check.webp",
    "w": 1400,
    "h": 1050,
    "blur": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAQAgCdASoQAAwAA8BgJQBOgMXIoHDNHzRAAPjdSTY8W6HJCrqUBjlHoihzdiugm7/XB3xqc6WDG3UQ1qciYjfiTPilAa387fJnVC34Ull8eIZ/UMOfSvJAAAA="
  },
  "two-wheeler-lab": {
    "src": "/img/two-wheeler-lab.webp",
    "w": 1800,
    "h": 1013,
    "blur": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAwAgCdASoQAAkAA8BgJbACdAYvXdv++oeOAAD9/OwvJfRLGF7eLMj5q1x413RDSFHgivCM8X9ggMoSOICx4ndT+aHRgeSaEYNKBmo4TST3teYFlX1d8u4N83/wAITFwAA="
  },
  "scooter-instruction": {
    "src": "/img/scooter-instruction.webp",
    "w": 1400,
    "h": 1050,
    "blur": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAABQAgCdASoQAAwAA8BgJagC7AYv1sR9vTxIcAAA/uqZ5qk/D7dBq8VTrxD+izyt4zb6JZpsUYhS+Fqn//LvtW2GRAIe7DyISWoLvaHeZaxX+G0sguoykxb9VOwAAA=="
  },
  "scooter-service": {
    "src": "/img/scooter-service.webp",
    "w": 1400,
    "h": 1050,
    "blur": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAQAgCdASoQAAwAA8BgJZwAD45OImbGU8XYAPa3j714Ao6xu+uPJKufDh/eHtzVjGoP27qrbob2IS83KoK+ITCww4OS/FdW15BsSkRv6Tzr0VeKtyOog5g4fgAAAA=="
  },
  "motorcycle-workshop": {
    "src": "/img/motorcycle-workshop.webp",
    "w": 1400,
    "h": 1050,
    "blur": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAAAQAgCdASoQAAwAA8BgJQBOgMWMpg39kpEAAP7wnQIGlqAJSLjeFu8p6RStR7tVim3uxIPr+FufWQKHFBZyCHlGwP3PVQoGglba2at3HI2aJbh0WLOU5KqmY/ULUzPBxf7+J8g4OEbAAA=="
  },
  "two-wheeler-demo": {
    "src": "/img/two-wheeler-demo.webp",
    "w": 1400,
    "h": 1050,
    "blur": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAwAgCdASoQAAwAA8BgJQBOgMYY37PMYIy8AAD+3/RhCQhrJ/nYEktrPsyhqOyTro/02U6kEEqocl1/2UWdjevvi0OMasQkTNtmmnarMVIfmZiBjWZftMhy9f6ArTqrGAAAAA=="
  },
  "healthcare-lab": {
    "src": "/img/healthcare-lab.webp",
    "w": 1400,
    "h": 1750,
    "blur": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAAAQBACdASoQABQAPwForE6rJaQiMAgBYCAJYwAIEAKm7DHZtlswNQaoYAD+t/l7r54AB0Mm/SnhNEv863pWqCuDAn0q3R15gGqfJxCLM6Xtf2icZbQ/vTSMrchuavplVYA7XersM4e2060Ae/NjRL009+t8ich6qCfi5WWcXcJC2GvREisVtenT2S3BwiAA"
  },
  "pathology-training": {
    "src": "/img/pathology-training.webp",
    "w": 1400,
    "h": 1050,
    "blur": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQAQCdASoQAAwAA8BgJZwAD4zHfp8pgAD+6KCjgLqNLyTE8N0DfLJpjrlaHAsbP/PE59PQOUlrCbTxR+RhOpYU+4aZWUcCVtbsIMl3J/mN5zSjuVY7TYAA"
  },
  "medical-camp": {
    "src": "/img/medical-camp.webp",
    "w": 1800,
    "h": 1013,
    "blur": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADQAQCdASoQAAkAA8BgJYwC7H8AC1N0UAD2vs7a1FqowSVrYmFNPtlmVzQHqc4RvywnLvcEuDe2tp7wB9AyEF4J3WNehQRXL49rML4Cvv04v6ZgAAA="
  },
  "medical-camp-community": {
    "src": "/img/medical-camp-community.webp",
    "w": 1400,
    "h": 1050,
    "blur": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAAAwAgCdASoQAAwAA8BgJQBOgMVuwBEW3gFJUAD+mm1MnreTu7+KTqUOBbYovBOxX2A06+VKcrPpYk34sCNxd4Fo1uKJSCzynX6uEYIs48dq3FiAQXnClobW+slfO1f8NKJxvpM+C7cH8YBAEAQ2x00AAAA="
  },
  "vision-screening": {
    "src": "/img/vision-screening.webp",
    "w": 1400,
    "h": 1050,
    "blur": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAQAgCdASoQAAwAA8BgJYwCdADu866HOOIAAP7KVKtiJnzQFTtV/hsqjI1rTUIQAn5yr9Z7i8jXPfzN6F9ylWo7i3MI5i++PWmbZfTpEAA="
  },
  "cnc-operation": {
    "src": "/img/cnc-operation.webp",
    "w": 1400,
    "h": 1050,
    "blur": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAQCdASoQAAwAA8BgJZQAAsYv+RAHygAA/CWVyxf3VYemdYSc19WWcxc4D7qd1zEOWpxyfexo4n5ZTscZlJKNLLlRe9q5+l9OCZaCOmsh+lAgAAA="
  },
  "cnc-instruction": {
    "src": "/img/cnc-instruction.webp",
    "w": 1800,
    "h": 1013,
    "blur": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADQAQCdASoQAAkAA8BgJYgCdAC4KaCCwADifJ23X65YNA5LBsG5OliHlKPnqB+FBHBeO7wUec0cXiukgmdtSPZLnpbUbpnQhYW7CBZZVqzCb115N6AgAA=="
  },
  "milling-practical": {
    "src": "/img/milling-practical.webp",
    "w": 1400,
    "h": 1050,
    "blur": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQAQCdASoQAAwAA8BgJaAC7ACeoUMrAAD+kVR39DwT6cxOZlDXVtzYdGpNJxTuWMSpKU0parry1ttENgK6fGH83j1JsVwUQ5hb9AVMjrjV3b13PG2JgAAA"
  },
  "sheet-metal-bench": {
    "src": "/img/sheet-metal-bench.webp",
    "w": 1800,
    "h": 1013,
    "blur": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADQAQCdASoQAAkAA8BgJQBOgMV4d1/7YAD+xR2YD97ktflrwvvMvD7proF3VxSjYy4KrAIqdpvUS6Mz0aqF5RCTM/iTjs+qdWP1aYnAre3Tlwy+UK8jZMt2BbOQAA=="
  },
  "welding-shopfloor": {
    "src": "/img/welding-shopfloor.webp",
    "w": 1800,
    "h": 1013,
    "blur": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAQCdASoQAAkAA8BgJZQC7AYulGVAv0AA/rgLZjpG4o3yUn0Oxq0JC9qodvwjqxSBt+PY2UDUYN9wF1ZHafgN7yPOctOTjfIZNsMO6q/UsNJdwAA="
  },
  "welding-practical": {
    "src": "/img/welding-practical.webp",
    "w": 1400,
    "h": 1050,
    "blur": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAQCdASoQAAwAA8BgJbACdACjqms7cWAA99xkbVMwseGIe5G0KO6ayG7JTgBfkIdc+8z08kA3u9e+E8DZeasorxJ82bFa6R5/DYQvdxsJJAtLIAA="
  },
  "diagnostics-console": {
    "src": "/img/diagnostics-console.webp",
    "w": 1800,
    "h": 1013,
    "blur": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAQCdASoQAAkAA8BgJZQCsAD5h/XJ09gA/OV9VZq7bvPrzRp8At9mhxIvLQTyEYSffxVj91sxESLda6hzoQblV3L8slWvx5dAuUXdaFn289oA"
  },
  "engine-cutaway": {
    "src": "/img/engine-cutaway.webp",
    "w": 1800,
    "h": 1013,
    "blur": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADQAQCdASoQAAkAA8BgJQBWAMW+j3tuAAD9eIO/2LefmyOmy5Q0yBfyXz5re0KYQrN4Sl9gVXNzK6J9qBeFbR9iZPFr7x2S6jjW8pTKtO4AUZa98xReGAWAAAA="
  },
  "engine-rig-group": {
    "src": "/img/engine-rig-group.webp",
    "w": 1800,
    "h": 1013,
    "blur": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAQAgCdASoQAAkAA8BgJZQCdADdZZ2WslAAAP5b002Bygd5wqb8rCXI6zKJNC04IGLeWAfEpmM7f3QRAcVEZv6svQ5Nr6+FIiPGijO/wkSLOvFcMk48IAAA"
  },
  "engine-briefing": {
    "src": "/img/engine-briefing.webp",
    "w": 1400,
    "h": 1050,
    "blur": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAwAgCdASoQAAwAA8BgJZQAD48Rdm1G205cwAD2Q6GGCP7JbLrUn1+4skN0fJY0tyJPWlyWYBQIoMHrsOYRJAn1yrs5kzExLcEjNUV3cknnH+2nq5gQv+z8I3AOgAAA"
  },
  "diagnostics-group": {
    "src": "/img/diagnostics-group.webp",
    "w": 1800,
    "h": 1013,
    "blur": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAACwAQCdASoQAAkAA8BgJZACdABzbV8AAP7ib2DKiq+GkxruOlydF1nyCmx5vd8t2bLbXbjQVw7MbS/Jie6xrlZ5geqYV7x2wG7TAXwm4YWNbu+B/YeG8U9TjPAAAA=="
  },
  "mobile-van-engine": {
    "src": "/img/mobile-van-engine.webp",
    "w": 1800,
    "h": 1013,
    "blur": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAACwAQCdASoQAAkAA8BgJQBdgBMZYS/AAP62GcZi61S7X1i2yO/ECFXdLBm94PNc+VJQQpnd+LEH/qbPeBtfTa1pTWt3dzrNb7dw7xkQAAA="
  },
  "van-engine-instruction": {
    "src": "/img/van-engine-instruction.webp",
    "w": 1400,
    "h": 1050,
    "blur": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAACQAQCdASoQAAwAA8BgJZQAAasj5wAA/t8b/oz3sGgYpICvoUmFzUHLQSIZzlgWnRuZsoTM0GgrwFmQHxd388ZogOVDQ8qM2Xhwp2xAGn4MuF+Vplk/oeSUjrrEBYAA"
  },
  "hcv-engine-bay": {
    "src": "/img/hcv-engine-bay.webp",
    "w": 1800,
    "h": 1013,
    "blur": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoQAAkAA8BgJZQAAv9veFJ0jAAA/pk8Lf6MsddAqm3fGkE5lBgb6MUvoHDXyy1cxpYr5gDaHuy79GchYxUNLDKzwofmjdAEtgA="
  },
  "hcv-hands-on": {
    "src": "/img/hcv-hands-on.webp",
    "w": 1400,
    "h": 1050,
    "blur": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAwAgCdASoQAAwAA8BgJZQC7AEO7zpnWgzKkAD+38qHGmexOTAiGtGhDImg+vzLJZrpdlz8+LhNTxFLY0Vkf4cMQIKPnCcOGiVoliEeigc0HpTQHewSgAAA"
  },
  "mobile-classroom": {
    "src": "/img/mobile-classroom.webp",
    "w": 1800,
    "h": 1013,
    "blur": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAAAQAgCdASoQAAkAA8BgJZQC7H8AGBSieeAAAP7USMIxYWqc36zuKPzteiRj6+aljFX5tr+eIQLMyC7bl24UaDA4o4AAAA=="
  },
  "cohort-classroom": {
    "src": "/img/cohort-classroom.webp",
    "w": 1800,
    "h": 1013,
    "blur": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACQAQCdASoQAAkAA8BgJaACsABzcZAA9rheLyNPPV4qdmys5f4+fsF15awEo5Fx+/W7JJHYXVuj+EPJyEJwv9YlKUnokAAA"
  },
  "engine-stand-training": {
    "src": "/img/engine-stand-training.webp",
    "w": 1800,
    "h": 1013,
    "blur": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoQAAkAA8BgJagCdAEO5YQQkAAA/tT78D/J+54btPUvWVxN4wcpN7enL1zwKnKnCHF+U0zTrYkqBdeRGuuIq4hqFoLlg3HLIAA="
  },
  "engine-teardown": {
    "src": "/img/engine-teardown.webp",
    "w": 1400,
    "h": 1050,
    "blur": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAQCdASoQAAwAA8BgJZQAD5Gw51agTaQA/Nh2ZY1ktm91M9uLhttDD8oYy5IcpUMIfYn9BNRP0Yqr/JmRTrgud5PdGzNR/nM9bn2R+JpbWQeUD1WAAA=="
  },
  "component-demo": {
    "src": "/img/component-demo.webp",
    "w": 1400,
    "h": 1050,
    "blur": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAACwAQCdASoQAAwAA8BgJQAAOn6fAkIAAP7WGK8XTdyE3VrEFW2SAnsqC2ekA72I1bVEwjKVV5pVR6HEfl39//ktqL/e0ozxa7OuyAAA"
  },
  "engine-disassembly": {
    "src": "/img/engine-disassembly.webp",
    "w": 1400,
    "h": 1050,
    "blur": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQAgCdASoQAAwAA8BgJZQCw7DREm9ThbkAAPqQzuy2KNp5v7IFPAWctDdKPxRbJcDPS57UbIwL2Wwxj5/vWOM0Uj0wWDMDxa2CGjnA+lmo0aEpgAA="
  },
  "electrical-safety": {
    "src": "/img/electrical-safety.webp",
    "w": 1400,
    "h": 1050,
    "blur": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADQAQCdASoQAAwAA8BgJaACdAEGivPEMAD+iSTIg05cjInKkgMRQR0YX3q8AT5br9gLFQokA+2fU2a64d2xoMKpfQ+X4dXYVmYrHl+aUS9V+2zGDG8O5olql1dMZtTeTi1fCq+AAAA="
  },
  "electrical-bench": {
    "src": "/img/electrical-bench.webp",
    "w": 1800,
    "h": 1013,
    "blur": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAQCdASoQAAkAA8BgJQBOgCLaY+rWWQAA+53QKKP8BMfufXPmWoidHdEL5Fa65BcyomjchrjpdLgVksVtSbKWGjzLOwZ+iwT7iqgQJUnDGuJAAAA="
  },
  "site-safety-cohort": {
    "src": "/img/site-safety-cohort.webp",
    "w": 1800,
    "h": 1013,
    "blur": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoQAAkAA8BgJZQAD5AreM7fAAD2rt9ZkwdtXEKiWGqqvi0a0fDedF87cRKfRGP8I+g3G6ePO2d99qXaS1Mfk87wAFuAAA=="
  },
  "safety-briefing": {
    "src": "/img/safety-briefing.webp",
    "w": 1800,
    "h": 1013,
    "blur": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAAAQAgCdASoQAAkAA8BgJaAC7AD8ZCbFoSFgAPwkM+NCkpoL+sWX5pOaU0/qVFRGmT9XIucf5HZzajFPuacprvfwhXvwFQTFEAA="
  },
  "tailoring-floor": {
    "src": "/img/tailoring-floor.webp",
    "w": 1800,
    "h": 1013,
    "blur": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoQAAkAA8BgJZwAAvrGuwGVYAD9/SV+RsFTjSRyduN2dJoUHbQ/Q55frEKFqF2jASGf+CovPq3VyydXZq0YU8gKOQAAAA=="
  },
  "tailoring-hands": {
    "src": "/img/tailoring-hands.webp",
    "w": 1400,
    "h": 1050,
    "blur": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAwAgCdASoQAAwAA8BgJYwCdAYsZtveG9IZAADOO01EMjb8qAyA/14Yx0jKoWOHXLsMWgj0SjtQR4+fZreNUVQGJLOYBjJ1GyFoEy259mSW6VIe4ulZF7QA"
  },
  "packaging-line": {
    "src": "/img/packaging-line.webp",
    "w": 1400,
    "h": 1050,
    "blur": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoQAAwAA8BgJYwCsADjeLi9YAAA4lABvXKyQumNTASAf1Cox0viWkfRfqxKoShlKKNGGRi6i4/EAMhkRebnuGI5j7+icywAAAA="
  },
  "packaging-practical": {
    "src": "/img/packaging-practical.webp",
    "w": 1400,
    "h": 1050,
    "blur": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAQAgCdASoQAAwAA8BgJQBOgMWgpokSN1tAAPsbpG8lC/8zz5ulPolBw7lXozief8mV98w4aiF23RGKwejSw27+fuFNCwjfQaJRwYirZsD1f0xKIxyZlBmbjFV2BAAA"
  },
  "food-processing": {
    "src": "/img/food-processing.webp",
    "w": 1400,
    "h": 1050,
    "blur": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAACwAQCdASoQAAwAA8BgJQAB8dT2wyUAAP7uUkme6Y+5TH/bRlkd5UcTUZ+9ldBk1gvV7mSEZJppDNEl8caR2+UykfJdDkpwYtjZyo3IZdpp70dSNqstbIssuokx2ygYAAA="
  },
  "plumbing-workshop": {
    "src": "/img/plumbing-workshop.webp",
    "w": 1800,
    "h": 1013,
    "blur": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQAgCdASoQAAkAA8BgJYwCdAEf0giJdtLAAP7AfriOxOt+Pk8YwOupHf35OuL84X76hjclAf7lJUWyy5XExpnWStNpKn6X0KCjrO9wBezzANKAAAA="
  },
  "plumbing-practical": {
    "src": "/img/plumbing-practical.webp",
    "w": 1400,
    "h": 1050,
    "blur": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAAAQAgCdASoQAAwAA8BgJYgCdAYwdKzVBgVEAP7B1QHBwfIx0448jnAPjJP6XapV22JddZHqwyH7oul5Fm8pncX0Y3352fr8kjWwVPuRTax6QbC54owrMTK39uNaVHddjDNW8osJfcFAAA=="
  },
  "engine-hands-on": {
    "src": "/img/engine-hands-on.webp",
    "w": 1800,
    "h": 1013,
    "blur": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAQCdASoQAAkAA8BgJYgCdAYsZV2260AAzH0hV2yZ0rtiqeUcXvV5+TjbKcGyztZ7ReaY/FlqGb1kLTWUha3CEpm27lU93yOYlgbq4OigYuSpUAA="
  },
  "engine-block-demo": {
    "src": "/img/engine-block-demo.webp",
    "w": 1400,
    "h": 1050,
    "blur": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAAAQAgCdASoQAAwAA8BgJQBOgMXw5r1M/wQAAP5habGkYiUe25qT7sNUhIvcxfhXq/x/e7/g85jZgCtpJGXvOhMD9db90LdQL7eN/DAeAaE/rv6fYVmd0ozfz62j9ptguZiX/oA8zS4RMSHhKTcf8K+QgAA="
  },
  "farm-machinery": {
    "src": "/img/farm-machinery.webp",
    "w": 1800,
    "h": 1013,
    "blur": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAQCdASoQAAkAA8BgJZQAAusax6PqAAD+4fMwAc56TXIoRCOc0lDIl7l+ZtcV3qE6asytTGXrgGKJCCS/EGM2VQL0TeT4AAA="
  },
  "farm-implement": {
    "src": "/img/farm-implement.webp",
    "w": 1400,
    "h": 1050,
    "blur": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADwAQCdASoQAAwAA8BgJYwCdADp/IRNDhAA/tYJ0KB9GoU+oudKx37O4p+2hk+lFcvhtfygc6nEp50tyC4KMwiAk9OxXWKzANUgvs89BKQgn2qmbOhKizQ3gAA="
  },
  "tractor-engine": {
    "src": "/img/tractor-engine.webp",
    "w": 1800,
    "h": 1013,
    "blur": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQAgCdASoQAAkAA8BgJYwC7H8AFVkwdWwAAP6Zg8WDYAkKL0rHmlc/VIPjxsMKnXvFp5cM9ncArxsvHRy8ACssyaRjWvb+wFeOyhmY/MVNbMZgAAA="
  },
  "tree-plantation": {
    "src": "/img/tree-plantation.webp",
    "w": 1400,
    "h": 1050,
    "blur": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAABQAgCdASoQAAwAA8BgJbACdAYulbSJnDqxqgAA/u4QFOM/gC+rUmt92dZQJfuRNW7jzVnn7R14vXOO2CzVjEu3Aq1EUhuGwJ4veYgDVT+cCkCLL/DcFOvx+PCwAAAA"
  },
  "plantation-hands": {
    "src": "/img/plantation-hands.webp",
    "w": 1400,
    "h": 1050,
    "blur": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAACwAgCdASoQAAwAA8BgJQBdj+Ef/DxcwL34qVrqmAAA/pd+JNrG5rQMq2lbztL/R9rqKTrF/GcJpEppjW5gZlfJPMx6oT2fna8neTBJPf6Y5yGmIQjSr8+umpYR1oKSaKC3qEgf4wJuYAAA"
  },
  "volunteer-cohort": {
    "src": "/img/volunteer-cohort.webp",
    "w": 1800,
    "h": 1013,
    "blur": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAwAgCdASoQAAkAA8BgJYgCdAEPEGrvbzgvwAD+56dhKbwxQoML09kEWz2gHCE2IVbXhQf8LNOM/fLQ0BW/TPnREMdNuiNz2P9EwgAA"
  }
} as const satisfies Record<string, Photo>;

export type PhotoKey = keyof typeof photos;
export const photo = (k: PhotoKey): Photo => photos[k];
