/**
 * Curates the programme photo archive into the site's image set.
 *
 *   node scripts/build-images.mjs
 *
 * Reads the raw archive at ARCHIVE, crops each selected frame to the aspect the
 * layout needs, trims any burnt-in GPS/date watermark off the bottom, writes
 * optimised webp to public/img, and regenerates src/lib/photos.ts with
 * dimensions and blur placeholders.
 *
 * The manifest below is a hand-picked selection: 61 frames out of 249, chosen
 * for subject clarity and the absence of watermarks that cropping cannot save.
 * Columns are [archiveIndex, slug, aspect(w/h), trimBottomPct, trimRightPct].
 * The two trims exist only to cut burnt-in GPS/date stamps out of frame.
 */
import sharp from 'sharp'; import fs from 'fs'; import path from 'path';
const ARCHIVE =
  process.env.ARCHIVE ?? '/Users/aryan/Projects/weldco/Photos for website';
const OUT = 'public/img';
fs.mkdirSync(OUT,{recursive:true});
// Archive index: every image file, sorted, 1-based — the numbering the
// manifest refers to.
function walk(d, acc = []) {
  for (const e of fs.readdirSync(d, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
    const p = path.join(d, e.name);
    if (e.isDirectory()) walk(p, acc);
    else if (/\.(jpe?g|png|webp)$/i.test(e.name)) acc.push(p);
  }
  return acc;
}
const archive = walk(ARCHIVE);
const src = (n) => archive[n - 1];

const M=[
  [121,'welding-sparks',16/9,0],
  [211,'engine-cohort',16/9,0],
  [57,'welding-bay',4/3,0],
  [58,'welding-shield',4/3,0],
  [134,'defence-engine-class',16/9,9],
  [135,'defence-mobile-unit',16/9,0],
  [137,'defence-assembly',16/9,0],
  [138,'helmet-engine-lab',4/3,0],
  [164,'mobile-training-unit',16/9,0],
  [72,'car-lift-training',4/5,0],  // portrait original: keeps car + cohort
  [73,'undercarriage-check',4/3,0],
  [198,'two-wheeler-lab',16/9,0],
  [195,'scooter-instruction',4/3,0],
  [84,'scooter-service',4/3,0],
  [202,'motorcycle-workshop',4/3,0],
  [66,'two-wheeler-demo',4/3,0],
  [145,'healthcare-lab',4/5,0],
  [147,'pathology-training',4/3,0],
  [115,'medical-camp',16/9,0],
  [118,'medical-camp-community',4/3,0],
  [193,'vision-screening',4/3,0],
  [49,'cnc-operation',4/3,0],
  [47,'cnc-instruction',16/9,0],
  [48,'milling-practical',4/3,0],
  [21,'sheet-metal-bench',16/9,0],
  [120,'welding-shopfloor',16/9,0],
  [157,'welding-practical',4/3,0],
  [106,'diagnostics-console',16/9,0],
  [101,'engine-cutaway',16/9,0],
  [105,'engine-rig-group',16/9,0],
  [108,'engine-briefing',4/3,0],
  [131,'diagnostics-group',16/9,9],
  [130,'mobile-van-engine',16/9,9],
  [172,'van-engine-instruction',4/3,0],
  [241,'hcv-engine-bay',16/9,0],
  [245,'hcv-hands-on',4/3,0],
  [249,'mobile-classroom',16/9,0],
  [174,'cohort-classroom',16/9,34],  // trim past the empty foreground table
  [213,'engine-stand-training',16/9,0],
  [216,'engine-teardown',4/3,0],
  [215,'component-demo',4/3,0],
  [208,'engine-disassembly',4/3,0],
  [152,'electrical-safety',4/3,17,10],
  [153,'electrical-bench',16/9,16,13],
  [154,'site-safety-cohort',16/9,0],
  [159,'safety-briefing',16/9,24,14],
  [27,'tailoring-floor',16/9,13],
  [29,'tailoring-hands',4/3,20],  // clears the phone-camera watermark
  [97,'packaging-line',4/3,0],
  [99,'packaging-practical',4/3,0],
  [92,'food-processing',4/3,21],   // clears the GPS Map Camera stamp
  [13,'plumbing-workshop',16/9,0],
  [17,'plumbing-practical',4/3,0],
  [4,'engine-hands-on',16/9,0],
  [8,'engine-block-demo',4/3,0],
  [223,'farm-machinery',16/9,0],
  [224,'farm-implement',4/3,0],
  [226,'tractor-engine',16/9,0],
  [179,'tree-plantation',4/3,0],
  [180,'plantation-hands',4/3,0],
  [181,'volunteer-cohort',16/9,0],
];

const man={};
for(const [n,slug,aspect,trim,trimR=0] of M){
  const im=sharp(src(n)).rotate();
  const meta=await im.metadata();
  let W=meta.autoOrient?.width??meta.width, H=meta.autoOrient?.height??meta.height;
  let pipe=sharp(src(n)).rotate();
  if(trim>0||trimR>0){
    const h=Math.round(H*(1-trim/100));
    const w=Math.round(W*(1-trimR/100));
    pipe=pipe.extract({left:0,top:0,width:w,height:h});
    W=w; H=h;
  }
  const targetW = aspect>=1.5?1800:1400;
  const targetH = Math.round(targetW/aspect);
  const buf=await pipe.resize(targetW,targetH,{fit:'cover',position:'centre'}).webp({quality:76,effort:5}).toBuffer();
  fs.writeFileSync(path.join(OUT,slug+'.webp'),buf);
  const blur=await sharp(buf).resize(16,Math.max(1,Math.round(16/aspect))).webp({quality:35}).toBuffer();
  man[slug]={src:`/img/${slug}.webp`,w:targetW,h:targetH,blur:`data:image/webp;base64,${blur.toString('base64')}`};
  process.stdout.write('.');
}
fs.mkdirSync('src/lib',{recursive:true});
fs.writeFileSync('src/lib/photos.ts',
`// AUTO-GENERATED by scripts/build-images.mjs — do not edit by hand.\n// Curated selection from the programme photo archive, 2020–2026.
export type Photo = { src: string; w: number; h: number; blur: string };

export const photos = ${JSON.stringify(man,null,2)} as const satisfies Record<string, Photo>;

export type PhotoKey = keyof typeof photos;
export const photo = (k: PhotoKey): Photo => photos[k];
`);
console.log('\n', Object.keys(man).length, 'images');
