/**
 * Normalises brand artwork for the site.
 *
 *   node scripts/build-brand.mjs
 *
 * Client logos arrive at wildly different sizes (150×40 to 5148×1368) with
 * inconsistent transparent padding. Rendering those at one CSS height makes
 * square marks look tiny next to wide wordmarks, so each logo is trimmed, then
 * scaled by an *optical* factor derived from its aspect ratio and padded onto a
 * canvas of identical height. The page can then render every logo at the same
 * height and have them read as the same visual weight.
 *
 * Also emits a white silhouette of the YandNow wordmark for dark backgrounds,
 * built from the source file's own alpha channel so the shape stays exact.
 */
import sharp from "sharp";
import fs from "fs";
import path from "path";

const SRC_LOGOS = "public/y&now client logos";
const OUT_LOGOS = "public/logos";
const OUT_BRAND = "public/brand";
const CANVAS_H = 128; // asset height; the page scales this down uniformly
const MAX_W = 460;

/** filename stem → display name used for alt text. */
const NAMES = {
  asdc: "Automotive Skills Development Council",
  "asian-paints": "Asian Paints",
  "assam-building": "Assam Building & Other Construction Workers Welfare Board",
  astral: "Astral Pipes",
  bcpl: "BCPL",
  "bharat-petroleum": "Bharat Petroleum",
  "bhartiya-vayu-sena": "Indian Air Force",
  boeing: "Boeing",
  bsf: "Border Security Force",
  castrol: "Castrol",
  cgsc: "Chhattisgarh Skill Development Council",
  credai: "CREDAI",
  crisp: "CRISP",
  csdc: "Construction Skill Development Council",
  "dilip-buildocon": "Dilip Buildcon",
  envalior: "Envalior",
  "essilor-luxottica": "EssilorLuxottica",
  "godrej-aerospace": "Godrej Aerospace",
  hettich: "Hettich",
  "indian-army": "Indian Army",
  "indian-oil": "Indian Oil",
  jaquar: "Jaquar",
  jsw: "JSW",
  mssds: "Meghalaya State Skill Development Society",
  "north-eastern-council": "North Eastern Council",
  nsdc: "National Skill Development Corporation",
  orientbell: "Orientbell Tiles",
  "reliance-foundation": "Reliance Foundation",
  "shreeji-infra": "Shreeji Infrastructure",
  tata: "Tata",
  "total-energies": "TotalEnergies",
  veedol: "Veedol",
  wmpsc: "Water Management and Plumbing Skill Council",
};

/** Wide wordmarks need less height than square marks to read as equal weight. */
function opticalScale(aspect) {
  if (aspect >= 3.4) return 0.56;
  if (aspect >= 2.4) return 0.7;
  if (aspect >= 1.6) return 0.84;
  return 1;
}

fs.mkdirSync(OUT_LOGOS, { recursive: true });
fs.mkdirSync(OUT_BRAND, { recursive: true });

const manifest = [];

for (const file of fs.readdirSync(SRC_LOGOS).sort()) {
  if (!/\.(png|jpe?g|webp)$/i.test(file)) continue;
  const slug = file
    .replace(/\.(png|jpe?g|webp)$/i, "")
    .replace(/[_\s]?logo$/i, "")
    .trim();

  const src = path.join(SRC_LOGOS, file);
  // Trim the transparent margin so the optical maths sees the artwork itself.
  const trimmed = await sharp(src).ensureAlpha().trim({ threshold: 6 }).toBuffer();
  const m = await sharp(trimmed).metadata();
  const aspect = m.width / m.height;
  const targetH = Math.round(CANVAS_H * opticalScale(aspect));

  const scaled = await sharp(trimmed)
    .resize({ height: targetH, width: MAX_W, fit: "inside", withoutEnlargement: false })
    .toBuffer();
  const sm = await sharp(scaled).metadata();

  const top = Math.round((CANVAS_H - sm.height) / 2);
  const out = await sharp(scaled)
    .extend({
      top,
      bottom: CANVAS_H - sm.height - top,
      left: 0,
      right: 0,
      background: { r: 0, g: 0, b: 0, alpha: 0 },
    })
    .webp({ quality: 92, alphaQuality: 100 })
    .toBuffer();

  fs.writeFileSync(path.join(OUT_LOGOS, `${slug}.webp`), out);
  const fm = await sharp(out).metadata();
  manifest.push({ slug, name: NAMES[slug] ?? slug, w: fm.width, h: fm.height });
  process.stdout.write(".");
}

/* ── YandNow wordmark ───────────────────────────────────── */
const brand = await sharp("public/logo.png").ensureAlpha().trim({ threshold: 6 }).toBuffer();
const bm = await sharp(brand).metadata();
await sharp(brand).webp({ quality: 95, alphaQuality: 100 }).toFile(path.join(OUT_BRAND, "yandnow.webp"));

// White silhouette: keep the source alpha, replace every colour with white.
const alpha = await sharp(brand).extractChannel("alpha").toBuffer();
await sharp({
  create: { width: bm.width, height: bm.height, channels: 3, background: "#ffffff" },
})
  .joinChannel(alpha)
  .webp({ quality: 95, alphaQuality: 100 })
  .toFile(path.join(OUT_BRAND, "yandnow-white.webp"));

manifest.sort((a, b) => a.name.localeCompare(b.name));

fs.writeFileSync(
  "src/lib/brand.ts",
  `// AUTO-GENERATED by scripts/build-brand.mjs — do not edit by hand.
export type ClientLogo = { slug: string; name: string; w: number; h: number };

/** Client and partner logos, normalised to a common optical height. */
export const clientLogos: ClientLogo[] = ${JSON.stringify(manifest, null, 2)};

/** Every logo asset shares this intrinsic height; width varies. */
export const LOGO_H = ${CANVAS_H};

export const wordmark = {
  colour: { src: "/brand/yandnow.webp", w: ${bm.width}, h: ${bm.height} },
  white: { src: "/brand/yandnow-white.webp", w: ${bm.width}, h: ${bm.height} },
};
`,
);

console.log(`\n${manifest.length} client logos, wordmark ${bm.width}x${bm.height}`);
